name: Run ZenSearch Scraper

on:
  schedule:
    - cron: "0 0 */2 * *"  # Runs at midnight every 2nd day
  workflow_dispatch:        # Manual trigger for testing

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Ensures we can commit back to the repo

      - name: Run Scraper
        run: node zensearch.js run  # Runs your scraper directly

      - name: Commit Results
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Auto-scraped job data [$(date)]" || echo "No changes to commit"
          # Only push if there were changes
          git diff --quiet || git push
